# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3910b0686886a0db7769c8769d2fce11c8ebcf596fca4810587f3518e607aa6de2dd8c6d075cffc9c84aec99f4c3288cfb84450448125a3d9063390a07a7a1d2

test:
  secret_key_base: bafe765a45f700fbac47cf21c61a9bfcc2e9f661bb076abf2597fdace9e0d5a8422ce3c371aa51f24e04a433301ba2e78a3563909a51d5a6bf872858e24ca78f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
